name: CI

on:
  push:
    branches: 
      - master


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: jorelali/setup-elm@v1
      with:
        elm-version: 0.19.1
    - run: git clone https://github.com/Sweaty-Bacon-Ducks/BusinessCard
    - run: cd BusinessCard; chmod +x build.sh; ./build.sh
    - run: cd BusinessCard; git subtree push --prefix SBDPAge origin gh-pages
